name: ekeel_aug_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - filelock=3.13.1
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=4.25.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - pytorch=2.3.1
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - bcrypt==4.2.1
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - conllu==6.0.0
      - defusedxml==0.7.1
      - dnspython==2.7.0
      - email-validator==2.2.0
      - flask==2.2.5
      - flask-httpauth==4.8.0
      - flask-mail==0.10.0
      - flask-mongoengine==1.0.0
      - flask-wtf==1.2.2
      - frozendict==2.4.6
      - idna==3.10
      - itsdangerous==2.2.0
      - json5==0.10.0
      - lxml==5.3.0
      - mongoengine==0.29.1
      - pandas==2.2.3
      - pyjwt==2.10.1
      - pyld==2.0.4
      - pymongo==4.10.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - rdflib==7.1.1
      - requests==2.32.3
      - six==1.17.0
      - tzdata==2024.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wtforms==3.2.1
      - youtube-transcript-api==0.6.3
